title: "DC Bootcamp 2024 - Tableau"
description: "DC Bootcamp 2024 - Tableau"
baseurl: "/dcbootcamp2024/tableau" # Update if necessary
url: "https://msdorachua.github.io" # Your GitHub Pages URL
theme: minima
